name: coffebreak_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  logger: ^2.4.0
  provider: ^6.1.2
  camera: ^0.10.0+4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/MyIcon2.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/MyIcon.svg
    - assets/icon/Estrella1.svg
    - assets/icon/Estrella2.svg
    - assets/recipes.json
    - assets/icon/ColdBrew.jpg
    - assets/icon/espresso.jpg
    - assets/icon/Latte.jpg
    - assets/icon/Cappuccino.jpg
    - assets/usabilidad.json
